name: Arduino Lint

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ArduinoLint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # all jobs should run
      matrix:
        board:
          - fqbn: arduino:avr:nano
            platform: arduino:avr

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh -s 0.34.0
          echo "./bin" >> $GITHUB_PATH

      - name: Install board
        run: |
          arduino-cli config init
          arduino-cli config set library.enable_unsafe_install true
          if [ -n "${{ matrix.board.url }}" ]; then
            arduino-cli config add board_manager.additional_urls ${{ matrix.board.url }}
          fi
          arduino-cli core update-index
          arduino-cli core install ${{ matrix.board.platform }}

      # - name: Install libraries
      #   run: |

      - name: Run test
        run: arduino-cli compile --library . -b ${{ matrix.board.fqbn }} ./test/ArduinoLint/ArduinoLint.ino
